const emojipedia = [
  {
    id: 1,
    tag: ["lol", "haha", "funny", "joy"],
    emoji: "😂",
    name: "Face with Tears of Joy",
    meaning: "Extreme happiness, laughter",
  },
  {
    id: 2,
    tag: ["heart", "love"],
    emoji: "❤️",
    name: "Heavy Black Heart",
    meaning: "Love",
  },
  {
    id: 3,
    tag: ["haha", "lol"],
    emoji: "🤣",
    name: "Rolling on the Floor Laughing",
    meaning: "Hysterical laughter",
  },
  {
    id: 4,
    tag: ["like", "thumb"],
    emoji: "👍",
    name: "Thumbs Up Sign",
    meaning: "Well done, good job, approval",
  },
  {
    id: 5,
    tag: ["sad", "crying", "cry"],
    emoji: "😭",
    name: "Loudly Crying Face",
    meaning: "Uncontrollable sadness, joy",
  },
  {
    id: 6,
    tag: ["pray", "thank you", "thank"],
    emoji: "🙏",
    name: "Person with Folded Hands",
    meaning: "Prayer, thank you, high five",
  },
  {
    id: 7,
    tag: ["kiss", "love"],
    emoji: "😘",
    name: "Face Throwing a Kiss",
    meaning: "Kiss, love",
  },
  {
    id: 8,
    tag: ["hearts", "love", "heart", "adoration"],
    emoji: "🥰",
    name: "Smiling Face with Smiling Eyes and Three Hearts",
    meaning: "Love, affection",
  },
  {
    id: 9,
    tag: ["affection", "love", "heart", "beautiful"],
    emoji: "😍",
    name: "Smiling Face with Heart-Shaped Eyes",
    meaning: "Love, adoration",
  },
  {
    id: 10,
    tag: ["positive", "happy", "smile"],
    emoji: "😊",
    name: "Smiling Face with Smiling Eyes",
    meaning: "Positive, happy",
  },
  {
    id: 11,
    tag: ["cry", "please", "uh"],
    emoji: "🥺",
    name: "Face with Pleading Eyes",
    meaning: "Adoration, bashful, pleading",
  },
  {
    id: 12,
    tag: ["hayst", "no", "daym", "face"],
    emoji: "🤦",
    name: "Face Palm",
    meaning: "Frustrated, dumbfounded",
  },
  {
    id: 13,
    tag: ["duh", "face", "fuck", "no way"],
    emoji: "🙄",
    name: "Face with Rolling Eyes",
    meaning: "Sarcasm, boredom",
  },
];

export default emojipedia;
